### ISSUE TITLE
折叠代码

### ISSUE THREAD

**Issue by GoDotDotDot** [nft4metaverse/m7e#46]
JSX:

```JSX
import React from 'react';
import classnames from 'classnames';
import Collapsible from 'react-collapsible';
import { useWalletProvider } from '@/components/web3modal';
import Footer from '@/components/v2/footer';
import smile2 from '@/assets/images/smile2.png';
import star2 from '@/assets/images/star2.png';
import up from '@/assets/images/up.png';
import down from '@/assets/images/down.png';
import bg3 from '@/assets/images/bg3.png';

import styles from './styles.less';

const CollapseItem = ({ question, children, openIndex, onToggle, index }) => {
  const active = openIndex === index;

  const onToggleHandler = React.useCallback(() => {
    onToggle(active ? -1 : index);
  }, [onToggle, index, active]);

  const Header = (
    <div
      className={classnames('flex w-full items-center px-2 sm:px-4 cursor-pointer', {
        'text-black': active,
        'text-white': !active,
      })}
      onClick={onToggleHandler}
    >
      <span className="text-2xl sm:text-2xl 2xl:text-4xl mr-4 font-kumar-one">0{index}</span>
      <div className="flex items-end flex-1">
        <span className="text-base sm:text-xl 2xl:text-2xl flex-1 sm:-mb-1 2xl:-mb-2 font-light leading-normal font-normal	">
          {question}
        </span>
      </div>
      <img style={{ width: 16, height: 10 }} src={active ? up : down} />
    </div>
  );

  return (
    <Collapsible
      trigger={Header}
      className={classnames('text-white py-2 sm:py-4', styles['border-bottom'], {
        [styles['no-border']]: active || openIndex - index === 1,
      })}
      openedClassName={classnames(styles['collapse-high'], 'rounded-lg py-2 sm:py-4')}
      open={active}
    >
      <div
        className={classnames(
          'pl-12 sm:pl-16 2xl:pl-20 pt-4 sm:pt-4 text-sm sm:text-lg 2xl:text-xl font-light',
          {
            'text-black': active,
            'text-white': !active,
          },
        )}
      >
        {children}
      </div>
    </Collapsible>
  );
};

export default function Section() {
  const ctx = useWalletProvider();
  const [openIndex, setOpenName] = React.useState(1);

  const onToggle = React.useCallback(
    (name) => {
      setOpenName(name);
    },
    [null],
  );

  return (
    <section className="relative w-full bg-black	">
      <div
        className="flex flex-col items-center w-full h-full px-4 "
        style={{ background: `url(${bg3}) 100% 100% / contain no-repeat` }}
      >
        <div className="flex w-full justify-center items-center pt-10 sm:pt-14 2xl:pt-20">
          <img
            src={star2}
            className="w-12 h-12 sm:w-18 2xl:w-24 sm:h-18 2xl:h-24 mr-6 animate-pulse"
          />
          <img src={smile2} className="w-10 h-10 2xl:w-20 2xl:h-20 sm:w-16 sm:h-16 mr-6" />
          <span className="text-white text-3xl sm:text-3xl  2xl:text-6xl mr-6 font-kumar-one">
            QA
          </span>
          <img src={smile2} className="w-10 h-10 2xl:w-20 2xl:h-20 sm:w-16 sm:h-16 mr-6" />
          <img src={star2} className="w-12 h-12 sm:w-18 2xl:w-24 sm:h-18 2xl:h-24 animate-pulse" />
        </div>

        <div className={classnames('w-full max-w-2xl mt-4 sm:mt-10 flex-1')}>
          {/* <Collapsible trigger="Start here" className={getCollapseCls()}>
          <p>This is the collapsible content. It can be any element or React component you like.</p>
          <p>It can even be another Collapsible component. Check out the next section!</p>
        </Collapsible> */}
          <CollapseItem
            question="What is MagicGoat NFT?"
            index={1}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            MagicGoat NFT is the genesis NFT of the GOATNFT platform. Through minting MagicGoat
            boxes, fragments and decorations are obtained to compose a complete MagicGoat NFT.
          </CollapseItem>

          <CollapseItem
            question="How many MagicGoat boxes will be minted in total?"
            index={2}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            8192 MagicGoat boxes will be minted.
          </CollapseItem>
          <CollapseItem
            question="What’s the price for MagicGoat box?"
            index={3}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            Every MagicGoat box will be sold at the price of 0.05 ETH.
          </CollapseItem>
          <CollapseItem
            question="When will MagicGoat box be issued?"
            index={4}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            September 15 at 15:00 UTC
          </CollapseItem>
          <CollapseItem
            question="Where will the minted MagicGoat Box be displayed?"
            index={5}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            The minted MagicGoat box will appear in your Ethereum address, and you can check it
            through wallet or opensea.
          </CollapseItem>
          <CollapseItem
            question="Is there a limit on the number of mints for each address?"
            index={6}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            A maximum of twenty MagicGoat Boxes can be minted once.
          </CollapseItem>
          <CollapseItem
            question="Where will MagicGoat be stored?"
            index={7}
            openIndex={openIndex}
            onToggle={onToggle}
          >
            MagicGoat is stored as an ERC-721 token on the Ethereum blockchain and the metadata was
            stored on IPFS.
          </CollapseItem>
        </div>
        <div className="main-content">
          <Footer />
        </div>
      </div>
    </section>
  );
}
```

Less:

```less
.bottom {
  height: 128px;
  background-image: linear-gradient(135deg, #2365f0 0%, #793aff 52%, #ff712c 100%);
}

.merge-bottom {
  flex-basis: 300px;
  flex-grow: 0;
  flex-shrink: 0;
  height: 300px;
  background-image: linear-gradient(135deg, #2365f0 0%, #793aff 52%, #ff712c 100%);
}

.collapse-high {
  background-image: linear-gradient(135deg, #2365f0 0%, #793aff 52%, #ff712c 100%);
}

.divide > :not([hidden]) ~ :not([hidden]) {
  border-top: 1px solid #878b8e;
  border-bottom-width: 0;
}

.divide:last-child {
  border-bottom: none;
}

.border-bottom {
  border-bottom: 1px solid #878b8e;
}

.no-border {
  border-bottom: none;
}

.roadmap-bg {
  background: url('../../assets/images/sidebg.png') no-repeat;
  background-position-x: calc(100% - 6rem);
  background-size: 665px 805px;
}

.roadmap-bg2 {
  background: url('../../assets/images/roadmap.png') no-repeat;
  background-position-x: calc(100% - 6rem);
  background-position-y: calc(100% - 3rem);
  background-size: 137px 137px;
}

.mint-btn {
  border-top-left-radius: 0;
  border-bottom-left-radius: 0;
}

:global {
  .Collapsible:last-child {
    border-bottom: none;
  }
}

@media screen and (max-width: 768px) {
  .roadmap-bg {
    background-position-x: calc(100% + 6rem);
    background-position-y: 0.4rem;
    background-size: 333px 402px;
  }

  .roadmap-bg2 {
    background-position-x: calc(100% - 2rem);
    background-position-y: calc(100% - 2rem);
    background-size: 68px 68px;
  }

  .bottom {
    height: 228px;
  }
}

@media screen and (max-width: 1536px) {
  .merge-bottom {
    flex-basis: 200px;
    height: 200px;
  }
}
```
